# Generated by Django 5.1 on 2024-08-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_testcomment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
